server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 152.136.125.94
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        multiplier: 2
        initial-interval: 10000ms
        max-interval: 210000ms
      exchange: leyou.sms.exchange
    publisher-confirms: true
    port: 5672
ly:
  sms:
    accessKeyId: AKIDQcYv20rEajdPu9P4eo23ISk25sQp66d2
    accessKeySecret: SSDuY2HJBzXuqYCNIx1qpbQwKjibEb9S
    signName: 张帅博客
    verifyCodeTemplate: 926879
